# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.cache/wt [current_project]
set_property parent.project_path C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/MIE/Desktop/COMP541/Lab/Project/Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/display640x480.vh
read_mem {
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/dmem_etchasketch.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/dmem_screentest.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/smem_screentest.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/imem_screentest.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/imem_screentest_nopause.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/bmem_screentest.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/imem_etchasketch.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/imem_full-IO-test.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/dmem_full-IO-test.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/bmem_screentest1.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/smem_screentest1.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/smem.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/bmem.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/imem1.mem
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/dmem1.mem
}
read_verilog -library xil_defaultlib -sv {
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/new/ALU.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/imports/sources/accelerometer.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/Lab/adder.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/Lab/addsub.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/new/bitmapmem.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/clockdiv.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/new/comparision.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/controller.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/new/datapath.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/new/dmem.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/new/fulladder.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/system_verilog/imem.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/imports/Lab/keyboard.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/new/logical.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/new/memIO.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/mips.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/system_verilog/programloader.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/register_file.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/new/screenmem.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/new/shifter.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/imports/Lab/sound.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/system_verilog/uart.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/system_verilog/uart_rx.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/system_verilog/uart_tx.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/Lab/vgadisplaydriver.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/new/vgatimer.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/sources_1/imports/new/xycounter.sv
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/Lab/top.sv
}
read_vhdl -library xil_defaultlib {
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/imports/sources/ADXL362Ctrl.vhd
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/imports/sources/AccelArithmetics.vhd
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/imports/sources/AccelerometerCtl.vhd
  C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/sources_1/imports/imports/sources/SPI_If.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/accel.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/accel.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/keyboard.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/keyboard.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/led.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/led.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/sound.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/sound.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/clock.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/clock.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/reset.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/reset.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/vga.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/vga.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/system_verilog/constraints_both_board_versions.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/system_verilog/constraints_both_board_versions.xdc]

read_xdc C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/switches.xdc
set_property used_in_implementation false [get_files C:/Users/MIE/Desktop/COMP541/Lab/Project/Project.srcs/constrs_1/imports/Lab/switches.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
